### ISSUE TITLE
Cannot get translation from OpenAI with GPT Plus

### ISSUE THREAD

**Issue by DermXZ** [Last-Order/ai-ass-translator#1]
C:\Users\Dermon\Documents\aaa\gpt-ass-to-spanish\src\translator.js:161
                            throw new Error("Cannot get translation from OpenAI.");
                                  ^

Error: Cannot get translation from OpenAI.
    at Translator.<anonymous> (C:\Users\Dermon\Documents\aaa\gpt-ass-to-spanish\src\translator.js:161:35)
    at step (C:\Users\Dermon\Documents\aaa\gpt-ass-to-spanish\src\translator.js:33:23)
    at Object.throw (C:\Users\Dermon\Documents\aaa\gpt-ass-to-spanish\src\translator.js:14:53)
    at rejected (C:\Users\Dermon\Documents\aaa\gpt-ass-to-spanish\src\translator.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.15.0

I tested it with a free account and worked
PD: i run it with another prompt, that's becasuse the folder name it's different (it translates the .ass to spanish instead of chinese)

**Comment by Last-Order** [comment]
Since I don't have a plus account, could you please provide more details about the error? Specifically, can you share any error messages from the API?

**Comment by DermXZ** [comment]
How do I see that? It's the only error I see in cmd

**Comment by Last-Order** [comment]
Add code after this line: https://github.com/Last-Order/ai-ass-translator/blob/main/src/translator.ts#L70
```
console.log(result);
```
And see what happened.

**Comment by DermXZ** [comment]
Added the line but didn't see anything different that the previous error. Where is supposed to be the log?

**Comment by Last-Order** [comment]
I have included additional debug output in the latest version (1.3.1). Would you be able to test it and report any error messages that are displayed?

**Comment by DermXZ** [comment]
C:\Users\Dermon\Documents\ssssssssss\ai-ass-translator-main\src>tsc index.ts
error TS2468: Cannot find global value 'Promise'.

index.ts:2:18 - error TS2307: Cannot find module 'erii' or its corresponding type declarations.

2 import Erii from "erii";
                   ~~~~~~

index.ts:3:23 - error TS2307: Cannot find module 'path' or its corresponding type declarations.

3 import * as path from "path";
                        ~~~~~~

index.ts:4:21 - error TS2307: Cannot find module 'fs' or its corresponding type declarations.

4 import * as fs from "fs";
                      ~~~~

index.ts:9:38 - error TS2304: Cannot find name '__dirname'.

9         fs.readFileSync(path.resolve(__dirname, "../package.json")).toString()
                                       ~~~~~~~~~

index.ts:43:5 - error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.

43     async (ctx, options) => {
       ~~~~~~~~~~~~~~~~~~~~~~~~~

translator.ts:1:19 - error TS2307: Cannot find module 'axios' or its corresponding type declarations.

1 import axios from "axios";
                    ~~~~~~~

translator.ts:2:23 - error TS2307: Cannot find module 'lodash' or its corresponding type declarations.

2 import { chunk } from "lodash";
                        ~~~~~~~~

translator.ts:3:21 - error TS2307: Cannot find module 'fs' or its corresponding type declarations.

3 import * as fs from "fs";
                      ~~~~

translator.ts:5:29 - error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.

5 const sleep = (time) => new Promise((resolve) => setTimeout(resolve, time));
                              ~~~~~~~

translator.ts:46:4 - error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.

46 ): Promise<AssDialog[]> => {
      ~~~~~~~~~~~~~~~~~~~~

translator.ts:125:17 - error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.

125     translate = async (file: string) => {
                    ~~~~~~~~~~~~~~~~~~~~~~~~~


Found 12 errors in 2 files.

Errors  Files
     5  index.ts:2
     6  translator.ts:1

**Comment by Last-Order** [comment]
Are you compiling the project on your own? Simply install the dependencies and run `tsc --watch` **within the project directory** instead of `src` to begin development.

**Comment by DermXZ** [comment]
i did it but is the same problem, also which are the dependences?

**Comment by Last-Order** [comment]
did you run `npm install` ?

**Comment by DermXZ** [comment]
[13:00:17] Starting compilation in watch mode...

[13:00:18] Found 0 errors. Watching for file changes.

ok, now what?

**Comment by Last-Order** [comment]
In another shell session, attempt to run the script to translate any .ass files and observe any error messages that are displayed.

**Comment by DermXZ** [comment]
C:\Users\Dermon\Documents\ssssssssss\ai-ass-translator-main\src>tsc index.ts

C:\Users\Dermon\Documents\ssssssssss\ai-ass-translator-main\src>node index.js -t hola.ass --openai-api-key apikey
Get translation failed, retry 1
Get translation failed, retry 2
Get translation failed, retry 3
Get translation failed, retry 4
connect ECONNREFUSED ::1:80 undefined
Get translation failed, retry 5
C:\Users\Dermon\Documents\ssssssssss\ai-ass-translator-main\src\translator.js:164
                            throw new Error("Cannot get translation from OpenAI.");
                                  ^

Error: Cannot get translation from OpenAI.
    at Translator.<anonymous> (C:\Users\Dermon\Documents\ssssssssss\ai-ass-translator-main\src\translator.js:164:35)
    at step (C:\Users\Dermon\Documents\ssssssssss\ai-ass-translator-main\src\translator.js:33:23)
    at Object.throw (C:\Users\Dermon\Documents\ssssssssss\ai-ass-translator-main\src\translator.js:14:53)
    at rejected (C:\Users\Dermon\Documents\ssssssssss\ai-ass-translator-main\src\translator.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.15.0

apikey is the key i used

**Comment by DermXZ** [comment]
and the other window didn't change

**Comment by Last-Order** [comment]
the 1.3.0 version is broken, could you try the latest version 1.3.1?

**Comment by DermXZ** [comment]
Sorry for not answering, i think that the problem is that i cannot use the API Key because i didn't add the paying method (because of the free trial). In a few weeks i will test it again.
