### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by DarkstaIkers** [Last-Order/ai-ass-translator#2]
How to set it up to translate to another language?

**Comment by Last-Order** [comment]
Please try to customize the prompt
https://github.com/Last-Order/ai-ass-translator/blob/main/src/translator.ts#L48

**Comment by DarkstaIkers** [comment]
> Please try to customize the prompt https://github.com/Last-Order/ai-ass-translator/blob/main/src/translator.ts#L48

Worked! Thank you.

**Comment by DarkstaIkers** [comment]
Also, can we use the model: gpt-3.5-turbo-16k-0613?

**Comment by Last-Order** [comment]
https://github.com/Last-Order/ai-ass-translator/blob/main/src/translator.ts#L55 
You can customize the model here. BTW, if you are using the 16k model, you can consider increasing the batch size.

**Comment by DarkstaIkers** [comment]
Which value it'd be good for 16k model?

**Comment by Last-Order** [comment]
It depends on your text length of lines. Maybe you can try different values to see the quality of output.

**Comment by DarkstaIkers** [comment]
Alright. I've put batch size 60 and it's all good.
